apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: elasticcloud
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: elasticclouds.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: elasticcloud
        plural: elasticclouds
        singular: elasticcloud
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  env:
                    default: dev
                    description: |
                      Deploy Elastic Cloud for Kubernetes to specific environment.
                      Production includes autoscaling for both Elastic and Kibana.
                    pattern: ^(dev|prod)$
                    type: string
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/promise-elasticcloud/elasticcloud-configure-pipeline:v0.1.0
            name: elasticcloud-promise-pipeline
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/promise-elasticcloud/elasticcloud-configure-pipeline:v0.1.0
            name: elasticcloud-configure-pipeline
