#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

urls=(
    "https://download.elastic.co/downloads/eck/2.5.0/crds.yaml"
    "https://download.elastic.co/downloads/eck/2.5.0/operator.yaml"
)

mkdir -p ${PWD}/configure-pipeline/dependencies

for url in "${urls[@]}"; do
    curl -sL -o $PWD/configure-pipeline/dependencies/$(basename $url) $url
done
