---
apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: TBDNAME
  namespace: default
spec:
  elasticsearchRef:
    name: TBDNAME
  policies:
    - name: data-ingest
      roles: ["data", "ingest" , "transform"]
      resources:
        nodeCount: {min: 1, max: 3}
        cpu: {min: 1, max: 2}
        memory: {min: 2Gi, max: 3Gi}
        storage: {min: 1Gi, max: 5Gi}
    - name: ml
      roles:
        - ml
      resources:
        nodeCount: {min: 1, max: 3}
        cpu: {min: 1, max: 2}
        memory: {min: 2Gi, max: 3Gi}
        storage: {min: 1Gi, max: 5Gi}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: TBDNAME
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: kibana.k8s.elastic.co/v1
    kind: Kibana
    name: TBDNAME
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
