#!/usr/bin/env sh

set -ex

name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
env_type="$(yq eval '.spec.env // "dev"' /kratix/input/object.yaml)"

sed "s/TBDNAME/${name}/g" /tmp/transfer/baseline-resources.yaml > /kratix/output/baseline-resources.yaml
if [ $env_type = "prod" ]; then
    sed "s/TBDNAME/${name}/g" /tmp/transfer/autoscaling.yaml > /kratix/output/autoscaling.yaml
fi
